public: ../public
destination:
  javascripts: js
  stylesheets: css
sources:
  javascripts: js
  stylesheets: css

javascripts:
  application:
    - lib/modernizr-2.5.3
    - lib/jquery-1.7.1
    - lib/underscore-1.3.1
    - lib/backbone-0.9.1
    - lib/bootstrap/bootstrap-collapse
    - application
stylesheets:
  application:
    - lib/bootstrap
    - application